CREATE DATABASE IF NOT EXISTS Team20_DB;

CREATE TABLE INVENTORY(
Item_ID INT AUTO_INCREMENT PRIMARY KEY,
Prod_SKU VARCHAR(50) NOT NULL UNIQUE,
Item_Name VARCHAR(100) NOT NULL,
Prod_Description VARCHAR(400),
Prod_Quantity DECIMAL(5,2) NOT NULL DEFAULT 0,
Prod_UnitPrice Decimal (10,2) NOT NULL,
Last_Updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE USERS(
User_ID INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(100) NOT NULL UNIQUE,
Encrypted_Password VARCHAR(255),
User_FName VARCHAR(50) NOT NULL,
User_LNAME VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
Phone_Num VARCHAR(25) NOT NULL UNIQUE,
User_Type VARCHAR(30) NOT NULL,
User_Creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
User_LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SPONSORS(
Sponsor_ID INT AUTO_INCREMENT PRIMARY KEY,
Sponsor_Name VARCHAR(100) NOT NULL UNIQUE,
Sponsor_Email VARCHAR(100) NOT NULL,
Sponsor_Phone VARCHAR(20) NOT NULL,
Sponsor_Address VARCHAR(150) NOT NULL,
Sponsor_PointConversion INT NOT NULL DEFAULT 0.01
);

CREATE TABLE ADMINS(
User_ID INT PRIMARY KEY,
Security_Level INT NOT NULL DEFAULT 1,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID)
);

CREATE TABLE DRIVERS(
User_ID INT PRIMARY KEY,
License_Num VARCHAR(50) NOT NULL,
User_Points INT NOT NULL DEFAULT 0,
Sponsor_ID INT NOT NULL,
App_Status ENUM ("Received", "Denied", "Approved"),
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID),
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)
);

CREATE TABLE SPONSOR_USER(
User_ID INT PRIMARY KEY,
Sponsor_ID INT NOT NULL,
Security_Level INT NOT NULL DEFAULT 2,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID),
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)
);


CREATE TABLE ORDERS(
Order_ID INT AUTO_INCREMENT PRIMARY KEY,
Driver_ID INT NOT NULL,
Sponsor_ID INT NOT NULL, 
Order_Status ENUM("Pending", "Completed", "Cancelled") NOT NULL,
Order_CancelReason VARCHAR(100),
Total_Points INT NOT NULL,
OrderTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (Driver_ID) REFERENCES DRIVERS(User_ID),
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)
);

CREATE TABLE LINE_ITEMS(
Line_ID INT AUTO_INCREMENT PRIMARY KEY,
Item_ID INT NOT NULL,
Order_ID INT NOT NULL,
Prod_SKU VARCHAR(50) NOT NULL,
Item_Name VARCHAR(100) NOT NULL,
Price_Points INT NOT NULL,
Quantity INT NOT NULL DEFAULT 1,
FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID),
FOREIGN KEY (Item_ID) REFERENCES INVENTORY(Item_ID)
);




