CREATE DATABASE IF NOT EXISTS Team20_DB;

CREATE TABLE INVENTORY(
Item_ID INT AUTO_INCREMENT PRIMARY KEY,
Prod_SKU VARCHAR(50) NOT NULL UNIQUE,
Item_Name VARCHAR(100) NOT NULL,
Prod_Description VARCHAR(400),
Prod_Quantity INT NOT NULL DEFAULT 0,
Prod_UnitPrice Decimal (10,2),
Last_Updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE USERS(
User_ID INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(100) NOT NULL UNIQUE,
User_FName VARCHAR(50) NOT NULL,
User_LNAME VARCHAR(50) NOT NULL,
Encrypted_Password VARCHAR(255),
Email VARCHAR(100) NOT NULL UNIQUE,
Phone_Num VARCHAR(25) NOT NULL UNIQUE,
User_Type VARCHAR(30) NOT NULL
);

CREATE TABLE ADMINS(
User_ID INT PRIMARY KEY,
Security_Level INT NOT NULL DEFAULT 1,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID)
);

CREATE TABLE DRIVERS(
User_ID INT PRIMARY KEY,
License_Num VARCHAR(50) NOT NULL,
Driver_Sponsor VARCHAR(50) NOT NULL,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID)
);

CREATE TABLE SPONSOR_USER(
User_ID INT PRIMARY KEY,
Sponsor_ID INT NOT NULL,
Security_Level INT NOT NULL DEFAULT 2,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID),
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)
);






