DROP TABLE IF EXISTS LINE_ITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS SPONSOR_USER;
DROP TABLE IF EXISTS DRIVERS;
DROP TABLE IF EXISTS ADMINS;
DROP TABLE IF EXISTS SPONSORS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS INVENTORY;