CREATE DATABASE IF NOT EXISTS Team20_DB;

CREATE TABLE INVENTORY(
Item_ID INT AUTO_INCREMENT PRIMARY KEY,
Prod_SKU VARCHAR(50) NOT NULL UNIQUE,
Item_Name VARCHAR(100) NOT NULL,
Prod_Description VARCHAR(400),
Prod_UnitPrice Decimal (10,2) NOT NULL,
Sponsor_ID INT NOT NULL,
Product_Image_URL VARCHAR(500),
External_Product_ID VARCHAR(100),
Last_Updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID),
UNIQUE KEY unique_external_product (Sponsor_ID, External_Product_ID)
);

CREATE TABLE USERS(
User_ID INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(100) NOT NULL UNIQUE,
Encrypted_Password VARCHAR(255),
User_FName VARCHAR(50) NOT NULL,
User_LNAME VARCHAR(50) NOT NULL,
User_Email VARCHAR(100) NOT NULL UNIQUE,
User_Phone_Num VARCHAR(25) NOT NULL UNIQUE,
User_Type VARCHAR(30) NOT NULL,
User_Creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Session_Version INT NOT NULL DEFAULT 1,
Prev_Password VARCHAR(255),
User_LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SPONSORS(
Sponsor_ID INT AUTO_INCREMENT PRIMARY KEY,
Sponsor_Name VARCHAR(100) NOT NULL UNIQUE,
Sponsor_Email VARCHAR(100) NOT NULL,
Sponsor_Phone VARCHAR(20) NOT NULL,
Sponsor_Address VARCHAR(150) NOT NULL,
Sponsor_PointConversion DECIMAL(5,2) NOT NULL DEFAULT 0.01,
Sponsor_Creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Sponsor_MaxPoints INT NOT NULL DEFAULT 3000000
);

CREATE TABLE ADMINS(
User_ID INT PRIMARY KEY,
Security_Level INT NOT NULL DEFAULT 1,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID)
);

CREATE TABLE DRIVERS(
User_ID INT PRIMARY KEY,
License_Num VARCHAR(50) UNIQUE NOT NULL,
User_Points INT NOT NULL DEFAULT 0,
Sponsor_ID INT NOT NULL,
Is_Active BOOLEAN NOT NULL DEFAULT TRUE,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID),
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)
);

CREATE TABLE SPONSOR_USER(
User_ID INT PRIMARY KEY,
Sponsor_ID INT NOT NULL,
Security_Level INT NOT NULL DEFAULT 2,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID),
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)
);


CREATE TABLE ORDERS(
Order_ID INT AUTO_INCREMENT PRIMARY KEY,
Driver_ID INT NOT NULL,
Sponsor_ID INT NOT NULL, 
Order_Status ENUM("Pending", "Completed", "Cancelled") NOT NULL,
Order_CancelReason VARCHAR(100),
Total_Points INT NOT NULL,
OrderTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (Driver_ID) REFERENCES DRIVERS(User_ID),
FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)
);

CREATE TABLE LINE_ITEMS(
Line_ID INT AUTO_INCREMENT PRIMARY KEY,
Item_ID INT NOT NULL,
Order_ID INT NOT NULL,
Prod_SKU VARCHAR(50) NOT NULL,
Item_Name VARCHAR(100) NOT NULL,
Price_Points INT NOT NULL,
Line_Quantity INT NOT NULL DEFAULT 1,
FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID),
FOREIGN KEY (Item_ID) REFERENCES INVENTORY(Item_ID)
);

CREATE TABLE NOTIFICATIONS(
Notification_ID INT PRIMARY KEY AUTO_INCREMENT,
Notification_Type VARCHAR(50) NOT NULL, 
User_ID INT NOT NULL,
Notification_Description VARCHAR(500) NOT NULL,
Notification_Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (User_ID) REFERENCES USERS(User_ID)
);

CREATE TABLE APPLICATIONS(
Application_ID INT AUTO_INCREMENT PRIMARY KEY,
App_Username VARCHAR(100) NOT NULL UNIQUE,
Encrypted_Password VARCHAR(255),
App_FName VARCHAR(50) NOT NULL,
App_LNAME VARCHAR(50) NOT NULL,
App_Email VARCHAR(100) NOT NULL UNIQUE,
App_Phone_Num VARCHAR(25) NOT NULL UNIQUE,
License_Num VARCHAR(50) UNIQUE NOT NULL,
App_Sponsor_ID INT NOT NULL,
App_Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
App_Status ENUM("Pending", "Approved", "Denied"),
FOREIGN KEY (App_Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID)

);

CREATE TABLE POINT_TRANSACTIONS(
Transaction_ID INT AUTO_INCREMENT PRIMARY KEY,
Driver_ID INT NOT NULL,
Actor_User_ID INT NOT NULL,
Points_Changed INT NOT NULL,
Reason VARCHAR(200) NOT NULL,
Transaction_Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (Driver_ID) REFERENCES DRIVERS(User_ID),
FOREIGN KEY (Actor_User_ID) REFERENCES USERS(User_ID)
);

CREATE TABLE AUDIT_LOGS(
Audit_ID INT AUTO_INCREMENT PRIMARY KEY,
Actor_ID INT NOT NULL,
Actee_ID INT NOT NULL,
Action_Type VARCHAR(500) NOT NULL,
Action_Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (Actor_ID) REFERENCES USERS(User_ID),
FOREIGN KEY (Actee_ID) REFERENCES USERS(User_ID)
);


CREATE TABLE SCHEDULED_POINT_EVENTS (
    Scheduled_Event_ID INT AUTO_INCREMENT PRIMARY KEY,
    Sponsor_ID INT NOT NULL,
    Driver_ID INT NOT NULL,
    Created_By INT NOT NULL,
    Event_ID INT,
    Event_Name VARCHAR(100) NOT NULL,
    Points_Change INT NOT NULL,
    Reason VARCHAR(200) NOT NULL,
    Scheduled_Time DATETIME NOT NULL,
    Processed_Time DATETIME,
    Scheduled_Status ENUM('Scheduled', 'Processed', 'Failed', 'Cancelled') NOT NULL DEFAULT 'Scheduled',
    FOREIGN KEY (Sponsor_ID) REFERENCES SPONSORS(Sponsor_ID),
    FOREIGN KEY (Driver_ID) REFERENCES DRIVERS(User_ID),
    FOREIGN KEY (Created_By) REFERENCES USERS(User_ID),
    FOREIGN KEY (Event_ID) REFERENCES POINT_EVENTS(Event_ID)
)
